language: dart
dart:
  - dev
  - beta
script:
  - dartanalyzer --fatal-infos --fatal-warnings ./lib ./test
  - dartfmt -n ./lib --set-exit-if-changed
  - pub get
  - pub global activate coverage
  - pub run --enable-asserts test/rx_storage_test.dart
  - dart
    --disable-service-auth-codes
    --enable-vm-service=8111
    --pause-isolates-on-exit
    --enable-asserts
    test/rx_storage_test.dart &
  - nohup pub global run coverage:collect_coverage
    --port=8111
    --out=coverage.json
    --wait-paused
    --resume-isolates
  - pub global run coverage:format_coverage
    --lcov
    --in=coverage.json
    --out=lcov.info
    --packages=.packages
    --report-on=lib
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
