name: rx_storage
description: Reactive storage for Dart/Flutter. RxDart Storage for Dart/Flutter.
version: 1.0.0-nullsafety.0
author: Petrus Nguyen Thai Hoc <hoc081098@gmail.com>
homepage: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
repository: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
issue_tracker: https://github.com/Flutter-Dart-Open-Source/rx_storage/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart_ext: ^0.0.1
  disposebag: ^1.5.0-nullsafety.1
  meta: ^1.3.0
  stack_trace: ^1.10.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  collection: ^1.15.0
