name: rx_storage
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  rxdart: '>=0.25.0 <0.26.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
