name: rx_storage
description: Reactive storage for Dart/Flutter. RxDart Storage for Dart/Flutter.
version: 2.1.0
homepage: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
repository: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
issue_tracker: https://github.com/Flutter-Dart-Open-Source/rx_storage/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=2.12.0 <4.0.0'

topics:
  - rxdart
  - hoc081098
  - rx-storage
  - reactive-storage
  - reactive-programming

dependencies:
  rxdart_ext: ^0.2.1
  disposebag: ^1.5.1
  meta: ^1.7.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  collection: ^1.16.0
