name: rx_storage
description: Reactive storage for Dart/Flutter. RxDart Storage for Dart/Flutter.
version: 0.0.1
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>
homepage: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
repository: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
issue_tracker: https://github.com/Flutter-Dart-Open-Source/rx_storage/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  rxdart: ^0.26.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
  collection: ^1.15.0-nullsafety.5
